### ISSUE TITLE
Create function to make a POST request to api/cluster/initialize and call it in the init command file

### ISSUE THREAD

**Issue by samlipari** [Sentinel-PaaS/Sentinel-CLI#14]
Hitting this endpoint from the init file will tell the API server to initialize the creation of the swarm

**Comment by Brendan-Leal** [comment]
Implemented in the last merge. Still needs to be tested

**Comment by Brendan-Leal** [comment]
Tested this endpoint along with the entire init command and it seems reliable. Closing issue
