### ISSUE TITLE
Initialize cluster with domain names

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/Sentinel-CLI#22]
When `sentinel init` is run, we need to ask the user for the (sub)domains they want to use for the traefik dashboard (assuming we want to give them access to this), the prometheus dashboard, and the grafana dashboard.

Presumably, we also need a command to update these domain names and re-run `stack-traefik-main.yml` to update those services, if they need to change those domains.

Currently, the domain names are hard-coded in `stack-traefik-main.yml`, and each of us needs to change them manually before using the API server to initialize anything.

**Comment by MFatigati** [comment]
From what I can tell, these domain names will need to initially be passed to `await api.initializeCluster()` on line 36 of `init.ts`

**Comment by Brendan-Leal** [comment]
`api.initializeCluster` takes no user input. It makes the API call to the server to start up the docker swarm infrastructure. Would asking for the domain be better in the `deploy` command?

**Comment by MFatigati** [comment]
Drew and I were talking about this... I know it doesn't take any input now, but it seems like it needs to. It's the spot where `stack-traefik-main.yml` is run, which sets up traefik/prom/grafana... whereas that file is NOT run on deploy (because you're just deploying a particular app).

The only alternative I can think of would be to leave all those host names blank initially, and provide a stand alone command, `sentinel domains`, which would allow them to be populated, and the update the stack. I think it would be ok to leave them blank, or with a dummy hostname, on start... but I'm not sure.

**Comment by dsessler7** [comment]
I don't think we want to have to worry about setting up domains

**Comment by MFatigati** [comment]
We would have to own that random domain, and point it at the manager node.

**Comment by MFatigati** [comment]
Can they be stored somewhere locally? Before `init`, the api server is not running, so it wouldn't be aware of the domains. They would still have to be sent to the API server at some point before traefik is loaded.

**Comment by samlipari** [comment]
Can grafana and prometheus be associated with a path instead of a host name instead? Like the label would be Path=(`/prometheus`) and we can tell users to go to that path to view their metrics? Or does it have to be a host?

**Comment by MFatigati** [comment]
`sentinel metrics`

```
Please enter the hostname you want to use to access your Traefik proxy dashboard (e.g., `traefik.yourdomain.com`):
Please enter the hostname you want to use to access your Prometheus metrics dashboard (e.g., `prometheus.yourdomain.com`):
Please enter the hostname you want to use to access your Grafana metrics dashboard (e.g., `grafana.yourdomain.com`):

As a reminder, you will need to have all these hostnames pointing to the following IP address: 11-22-33-44.

Please enter the password you want to use with all these dashboards (your username will be "admin"):
```

**Comment by MFatigati** [comment]
{
    "traefikHostName": "traefik-2.michaelfatigati.com",
    "prometheusHostName": "prometheus-2.michaelfatigati.com",
    "grafanaHostName": "grafana-2.michaelfatigati.com",
    "password": "test"
}

**Comment by samlipari** [comment]
Should this part be coming back in the successful server response?
"As a reminder, you will need to have all these hostnames pointing to the following IP address: 11-22-33-44."

**Comment by MFatigati** [comment]
Yes, I was thinking the same thing!
