### ISSUE TITLE
Rephrase language when asking for email

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/Sentinel-CLI#28]
I was just checking to see what variable will be passed to the API for the email, and noticed that the prompt says "Your application must use HTTPS." I know this is a VERY minor, maybe superficial thing, but to my ear it makes it sound like this imposes some burden on the user, when in reality we're doing this for them. So maybe just "Your application will automatically be configured with HTTPS. All we need from you is your email... blah blah blah".

**Comment by Brendan-Leal** [comment]
Definitely reads better now. Thanks
